receivers:
  otlp:
    protocols:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  elasticsearch:
    endpoints: ["http://es:9200"]
    logs_index: my_logs

  logging:
    loglevel: debug

  zipkin:
    endpoint: "http://host.docker.internal:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch, logging]
    traces:
      receivers: [otlp]
      exporters: [zipkin, logging]
